# Generated by Django 6.0.4 on 2026-04-23 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medico',
            name='especialidade',
            field=models.CharField(default='Clínico Geral', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='plano_de_saude',
            name='nome',
            field=models.CharField(choices=[('vip', 'Vip'), ('comum', 'Comum')], unique=True),
        ),
    ]
