# Generated by Django 6.0.4 on 2026-04-23 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_medico_especialidade_alter_plano_de_saude_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='medico',
            name='foto',
            field=models.URLField(default='https://placehold.co/300x300'),
            preserve_default=False,
        ),
    ]
