# Generated by Django 6.0.4 on 2026-04-23 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_medico_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medico',
            name='foto',
            field=models.CharField(max_length=200),
        ),
    ]
