# Generated by Django 6.0.4 on 2026-04-29 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0004_alter_medico_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='medico',
            name='crm',
            field=models.CharField(default='teste', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medico',
            name='descricao',
            field=models.CharField(default='teste', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medico',
            name='formacao',
            field=models.CharField(default='teste', max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medico',
            name='horario_atendimento',
            field=models.CharField(default='teste', max_length=30),
            preserve_default=False,
        ),
    ]
